version: '2.3'
services:
  kalki-iot-interface:
    extends:
      file: dist/kalki-iot-interface/docker-compose.yml
      service: kalki-main-controller
  kalki-iot-wemo:
    extends:
      file: dist/kalki-iot-interface/docker-compose.yml
      service: kalki-iot-wemo
  ovs-docker-service:
    extends:
      file: dist/ovs-docker-service/docker-compose.yml
      service: ovs-docker-service
