version: '2.0'
services:
  kalki-postgres:
    image: kalki/kalki-postgres
    container_name: kalki-postgres
    environment:
      - TZ=${HOST_TZ}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h kalki-postgres"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - kalki-pgdata:/var/lib/postgresql/data
  kalki-main-controller:
    image: kalki/kalki-main-controller
    container_name: kalki-main-controller
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    command: ${CMD_PARAMS}
    volumes:
      - ./logs:/logs
    depends_on:
      kalki-postgres:
        condition: service_healthy
  kalki-umbox-controller:
    image: kalki/kalki-umbox-controller
    container_name: kalki-umbox-controller
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    command: ${CMD_PARAMS}
    volumes:
      - ./logs:/logs
      - ./tests:/kalki-umbox-controller/tests
    depends_on:
      kalki-postgres:
        condition: service_healthy
  kalki-device-controller:
    image: kalki/kalki-device-controller
    container_name: kalki-device-controller
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    command: ${CMD_PARAMS}
    volumes:
      - ./logs:/logs
    depends_on:
      kalki-postgres:
        condition: service_healthy

volumes:
  kalki-pgdata:
    name: kalki-pgdata
