#!/usr/bin/env bash

export CONTROL_NIC=br-control
export IOT_NIC=eth1
export EXT_NIC=eth2

export CONTROL_NET_PREFIX=10.27.200
export IP_ON_CONTROL_NIC=${CONTROL_NET_PREFIX}.2

export CONTROL_IP_NET=${CONTROL_NET_PREFIX}.0/24
export CONTROL_GATEWAY=${CONTROL_NET_PREFIX}.1
export UMBOX_IP_RANGE=${CONTROL_NET_PREFIX}.128/25
