#!/bin/bash

file="/netplan_configs/$1-config.yaml"

cp $file /etc/netplan/01-config.yaml
netplan apply

echo " "
echo "Netplan config changed to $file"

if [[ $1 == "cl" ]]; then
	echo "Restart the machine to apply this change"
fi

echo " "
